language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install -d --system'
  - 'pip install coverage'
script:
  - 'coverage run tests.py'
after_success:
    - 'bash <(curl -s https://codecov.io/bash)'
    - 'python-codacy-coverage -r coverage.xml'
