language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
  - 'pipenv install --dev'
# script:
#   - 'pipenv run py.test tests'
after_success:
    - 'bash <(curl -s https://codecov.io/bash)'
    - 'python-codacy-coverage -r coverage.xml'
