language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
#   - 'pipenv install --dev'
  - 'pipenv sync'
  - 'django-admin --version'
  - 'pytest --version'
  - 'pip install coverage'
script:
  - 'coverage run tests.py'
#   - 'pipenv run py.test tests'
after_success:
    - 'bash <(curl -s https://codecov.io/bash)'
    - 'python-codacy-coverage -r coverage.xml'
