language: python
python:
  - '3.6'
install:
  - 'pip install pipenv'
#   - 'pipenv install --dev'
  - 'pipenv install -d --system'
script:
  -  'pytest --cov=./'
after_success:
    - 'bash <(curl -s https://codecov.io/bash)'
    - 'python-codacy-coverage -r coverage.xml'
